name: CI
on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install dependencies
        run: sudo apt update && sudo apt install libglfw3
      - name: Compile
        run: chmod +x make.sh && ./make.sh -DDO_TESTS
      - name: Test
        run: ./cpu.out

  Windows:
    runs-on: windows-2022
    steps:
      - name: Test Windows
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl