name: CI
on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install dependencies
        run: sudo apt install libglfw3-dev
      - name: Build
        run: g++ -std=c++20 -O2 -Isrc test/*.cpp src/cpu.cpp src/helpers.cpp -o testall
      - name: Run tests
        run: ./testall

  Windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install dependencies
        shell: cmd
        run: .\install.bat
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call cl /TP /EHsc /std:c++20 test/*.cpp src/cpu.cpp src/helpers.cpp /Fetestall
      - name: Run tests
        shell: cmd
        run: .\testall.exe
