name: CI
on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Test Linux
        run: |
          echo "hello"

  Windows:
    runs-on: windows-2019
    steps:
      - name: Test Windows
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl