name: CI
on: [push]

jobs:
  Linux:
    runs-on: ubuntu-23.04
    steps:
      - name: Test Linux
        run: |
          g++ --version

  Windows:
    runs-on: windows-2022
    steps:
      - name: Test Windows
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cl